namespace :mars_rover do
  task :default => [:test, :run]

  desc "Runs all the spec"
  task :test do
    cmd = "rspec spec"; puts cmd; system cmd
  end

  desc "Runs the mars_rover program with mars_rover.input as input"
  task :run do
    cmd = "ruby lib/mars_rover.rb mars_rover.input"; puts cmd; system cmd
  end
end
